### ISSUE TITLE
Check if olsrd is Running 

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/vpnconfig#1]
Sometimes olsrd crashes

**Comment by storchi** [comment]
pidof and routes counter?

**Comment by bittorf** [comment]
auf dem Router oder auf dem Server?

**Comment by andibraeu** [comment]
Am Freitag, den 23.05.2014, 00:29 -0700 schrieb Bastian Bittorf:

> auf dem Router oder auf dem Server?

Server...
Ich checke das zwar schon im Monitoring/Icinga, allerdings startet das
olsr nicht neu, wenn es nicht läuft.

**Comment by bittorf** [comment]
also "pidof olsrd >/dev/null || restart olsrd" sollte sein
ausserdem koennte man das olsrd-watchdog-plugin nutzen

**Comment by storchi** [comment]
looft

**Comment by bittorf** [comment]
@storchi im aktuellen olsrd v1 wird gerade ein crash gesucht. siehe mailingliste...

**Comment by storchi** [comment]
und? die checks sind eingebaut...
